## traefik.yml
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

# Docker configuration backend
providers:
  docker:
    network: dev

# API and dashboard configuration
api:
  insecure: true

accessLog: {}
