version: '2'
services:
  zookeeper:
    image: 'zookeeper'
    hostname: zookeeper
    container_name: zookeeper
#    ports:
#      - '2181:2181'

  kafka:
    image: 'wurstmeister/kafka'
    hostname: kafka
    container_name: kafka
#    ports:
#      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    hostname: kafkamanager
    container_name: kafkamanager
#    ports:
#      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
#      APPLICATION_SECRET: "random-secret"
    labels:
      traefik.http.routers.kafkamanger.rule: Host("kafka.localtest.me")
      traefik.http.services.kafkamanger.loadbalancer.server.port: 9000

networks:
  default:
    external:
      name: dev